### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by RebelCodeBase** [brona/iproute2mac#10]
Recently, this formula throws the following warning:

> Warning: Calling Formula.sha1 is deprecated!
> Use Formula.sha256 instead.
> /usr/local/Library/Taps/brona/homebrew-iproute2mac/iproute2mac.rb:6:in `<class:Iproute2mac>'
> Please report this to the brona/iproute2mac tap!

**Comment by brona** [comment]
Hi brona/Homebrew-iproute2mac tap is no longer supported see https://github.com/brona/homebrew-iproute2mac.

Homebrew formula for iproute2mac was merged into homebrew-core see https://github.com/Homebrew/homebrew-core/blob/master/Formula/iproute2mac.rb
