### ISSUE TITLE
ip help

### ISSUE THREAD

**Issue by babydonkey** [brona/iproute2mac#18]
hello! thank you for your work! i use it on macOS, when i input "ip help", it shows [Object "help" is unknown, try "ip help".]

**Comment by SimonTate** [comment]
I found that this was only when installed by homebrew. Installing from "source"  didn't have this issue for me.

**Comment by brona** [comment]
It was fixed in #19, which was already merged (That is why it works when install directly from the repo). I have to do a minor release someday, likely with the other issues fixed as well.
