### ISSUE TITLE
Error: Your CLT does not support macOS 11.0.

### ISSUE THREAD

**Issue by hkzj** [brona/iproute2mac#34]
Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
Error: An exception occurred within a child process:
  SystemExit: exit

**Comment by brona** [comment]
What command did you use? I can run ./test/commands.sh on macOS 11.0.1 (20B50) without any problems.

Perhaps it is a homebrew issue? https://github.com/Homebrew/brew/issues/8797
Or any chance you are running Beta version of macOS ?

**Comment by cranebytes** [comment]
@hkzj you need to uninstall your command line tools and then to reinstall them.
@brona this is not a bug within iproute2mac and this issue can be closed. :)
