### ISSUE TITLE
HomeBrew dependency messes with my system

### ISSUE THREAD

**Issue by dcc1165** [brona/iproute2mac#39]
PLEASE remove the python@3.10 dependency from the HomeBrew bundle.  Using `#!/usr/bin/env python3` is sufficient for this to run without HomeBrew poisoning systems with what it thinks is the "proper" version of Python.

Besides, anyone running this command should be system-savvy enough to ensure Python 3 is installed (in fact it's installed by default on MacOS Monterey).

**Comment by brona** [comment]
https://docs.brew.sh/Python-for-Formula-Authors#python-declarations

> Formulae for apps that require Python 3 should declare an unconditional dependency on "python@3.x". These apps must work with the current Homebrew Python 3.x formula.

This is actually managed by the homebrew team, see e.g. https://github.com/Homebrew/homebrew-core/commit/d1d03f156a6b9da3ced5e96ebfcb5ff1eb85dc1f
