### ISSUE TITLE
ip netns and ip tunnel

### ISSUE THREAD

**Issue by jxcang** [brona/iproute2mac#41]
While I appreciate the efforts in making system administrators' life easier for those coming from Linux to Mac, iproute2mac seems to lack the main course of iproute2, namely ip netns and ip tunnel main dishes.

ip tunnel is probably possible since Mac allows the creation of IPsec and GRE tunnels through the GUI. ip netns is more difficult, as MacOS isn't designed for namespace operations.

**Comment by brona** [comment]
As you are saying both of these are quite tricky, since they depend on how the networking stack works inside the OS.

iproute2mac probably won't support these anytime soon.

**Comment by brona** [comment]
Closing the FR for now.
