### ISSUE TITLE
Add support for -j (json) flag

### ISSUE THREAD

**Issue by stewartadam** [brona/iproute2mac#49]
Modern versions of `ip` support a `-j` flag to output as machine-readable JSON, would be great to have this on MacOS too!

**Comment by BloodyFrag** [comment]
+1. This would be great for custom scripts.

**Comment by signal-09** [comment]
I tried to implement it in 543fef9a9501ad782f03ad6d70f3c492e8b78ad2.
It is a bit rudimental but working. Not all the macOS `ifconfig` and `netstat` outputs are parsed, but enough to make some other project to work (e.g. vagrant-libvirt/vagrant-libvirt#1205 mentioned above).
