### ISSUE TITLE
running "ip -6 neigh" throws error

### ISSUE THREAD

**Issue by jbehrends** [brona/iproute2mac#5]
OSX 10.10.5 
Dual stack ipv4 / ipv6 environment

Running "ip -6 neigh" throws the below error after printing out a few entries:

    $ ip -6 neigh
    2601:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx dev en0 lladdr x:x:xx:xx:xx:xx STALE
    2601:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx dev en0 lladdr x:xx:xx:xx:xx:xx STALE
    2601:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx dev en0 lladdr xx:xx:xx:xx:xx:xx REACHABLE
    2601:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx dev en0 lladdr xx:xx:xx:xx:xx:xx REACHABLE
    2601:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx dev en0 lladdr xx:xx:xx:xx:xx:xx STALE
    Traceback (most recent call last):
      File "/usr/local/bin/ip", line 443, in <module>
        main(sys.argv[1:])
      File "/usr/local/bin/ip", line 437, in main
        do_neigh(argv,af)
      File "/usr/local/bin/ip", line 369, in do_neigh
        stat=statuses[ra[4]]
    KeyError: 'N'
    $

**Comment by jbehrends** [comment]
I ran "ndp -an" after seeing the error above, and the next two entries following the ones it successfully printed were:

    fe80::1%lo0                     (incomplete)         lo0 permanent R
    fe80::%en0                      (incomplete)         en0 expired   N

**Comment by brona** [comment]
Thanks for bug report, fixed in 14f5323 (v1.0.6)
